[package]
name = "crashfinder"
version = "0.1.0"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>"]
edition = "2018"
license = "MPL"

[dependencies]
clap = "2.33"
log = "0.4"
url = "2.0"
env_logger = "0.7"
wait-timeout = "0.1"
rayon = "1.2"
tempdir = "0.3"
walkdir = "2.2"
